apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskex-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskex-deploy
  strategy: {}
  template:
    metadata:
      labels:
        app: flaskex-deploy
    spec:
      containers:
      - image: ikambarov/flaskex
        name: flaskex
